# Site settings
title: Sergio Martin Rubio
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://sergiomartinrubio.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
remote_theme: YoussefRaafatNasry/portfolYOU

plugins:
  - jekyll-feed
# - jekyll-algolia

# algolia:
#   application_id: 09V6SYMNZX
#   index_name:     jekyll # You can replace that with whatever name you want
#   search_only_api_key: fb020dfbffad2bca00f9d84933e17a2f

# Author Info
author:
  name     : Sergio Martin Rubio
  image    : https://i.ibb.co/CmQVzwz/ATP7514.jpg
  email    : econsergio@gmail.com
  github   : smartinrub
  twitter  : smartinrub
  linkedin : sergiomartinrubio
  # facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name
  tutorials:
    output: true
    permalink: /tutorials/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock