# Site settings
title: Sergio Martin Rubio
description: >- # this means to ignore newlines until "baseurl:"
  Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.

url: "http://sergiomartinrubio.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""  # the subpath of your site, e.g. /blog
repository: smartinrub/sergio-martin-rubio-site
remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Sergio Martin Rubio
  image             : https://lh3.googleusercontent.com/OCZy-rLu7HRt0UEpGL3nYBD-SAAov6vbi8ox-1xbBuYhF9ivXdm7MTb4XTckkxic0pCOeAvCcc9Uxe949uwYznQZA2NbMrFfrsYW0cmgo_oStG5-pVmc7HjQnK-d4fCJg_ENuN5VhA=w600
# behance           : your_username
# dribbble          : your_username
  email             : me@sergiomartinrubio.com
# facebook          : your_username
  github            : smartinrub
# gitlab            : your_username
# instagram         : your_username
  linkedin          : sergiomartinrubio
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : smartinrubio
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"
paginate_path: "/tutorials/page-:num/"

### Posts Permalink ###
permalink: articles/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  privacy_policy: 
    output: true
    permalink: /privacy-policy/


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jemoji

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
